# Generated by Django 4.1.4 on 2023-03-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botao1', models.CharField(max_length=25, verbose_name='Botão 1')),
                ('botao2', models.CharField(max_length=25, verbose_name='Botão 2')),
                ('botao3', models.CharField(max_length=25, verbose_name='Botão 3')),
                ('botao4', models.CharField(max_length=25, verbose_name='Botão 4')),
                ('botao5', models.CharField(max_length=25, verbose_name='Botão 5')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Logo da empresa')),
                ('logo_titulo', models.CharField(max_length=25, verbose_name='Nome da empresa')),
                ('titulo_inicial', models.CharField(max_length=100)),
                ('paragrafo_inicial', models.TextField(max_length=200)),
                ('banner', models.ImageField(blank=True, upload_to='banner')),
            ],
            options={
                'verbose_name_plural': 'Seção 1 - Home',
            },
        ),
        migrations.CreateModel(
            name='Secao2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('saiba_mais', models.TextField(max_length=3000)),
                ('link', models.URLField(blank=True, null=True)),
                ('preco', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Secao 2 - Serviços',
            },
        ),
        migrations.CreateModel(
            name='Secao3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('paragrafo', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Seção 3 - Nosso diferencial',
            },
        ),
        migrations.CreateModel(
            name='Secao4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Seção 4 - Contatos',
            },
        ),
        migrations.CreateModel(
            name='Secao5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('paragrafo', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Seção 5 - Sobre a empresa',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Add seus serviços',
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AddField(
            model_name='secao2',
            name='itens',
            field=models.ManyToManyField(related_name='secao_servicos', to='plataforma.servicos'),
        ),
    ]
