# Generated by Django 4.1.4 on 2023-03-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_secao1_secao2_secao3_secao4_secao5_servicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao2',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
    ]
