# Generated by Django 4.1.4 on 2022-12-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_emailcontato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcontato',
            name='data',
        ),
    ]
