# Generated by Django 4.1.4 on 2023-03-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_alter_secao2_subtitulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secao2',
            options={'verbose_name_plural': 'Card Serviço'},
        ),
    ]
