# Generated by Django 4.1.4 on 2023-03-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_secao2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao1',
            name='botao1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Botão 1'),
        ),
        migrations.AlterField(
            model_name='secao1',
            name='botao2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Botão 2'),
        ),
        migrations.AlterField(
            model_name='secao1',
            name='botao3',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Botão 3'),
        ),
        migrations.AlterField(
            model_name='secao1',
            name='botao4',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Botão 4'),
        ),
        migrations.AlterField(
            model_name='secao1',
            name='botao5',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Botão 5'),
        ),
    ]
