# Generated by Django 4.1.4 on 2023-03-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_secao1_botao1_alter_secao1_botao2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao2',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secao2',
            name='saiba_mais',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secao2',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secao3',
            name='paragrafo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secao3',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secao5',
            name='paragrafo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='secao5',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
