# Generated by Django 4.1.4 on 2023-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_alter_plataforma_paragrafo_alter_plataforma_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesSicaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
