# Generated by Django 4.1.4 on 2023-01-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0007_informacoessicaf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformacoesSicaf',
        ),
    ]
