# Generated by Django 4.1.4 on 2023-01-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_delete_informacoessicaf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plataforma',
        ),
    ]
