# Generated by Django 4.1.4 on 2023-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_delete_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_inicial', models.CharField(max_length=50)),
                ('paragrafo_inicial', models.TextField(max_length=200)),
                ('preco_servico1', models.IntegerField()),
                ('preco_servico2', models.IntegerField()),
                ('sicaf_titulo', models.CharField(max_length=50)),
                ('sicaf_texto', models.TextField()),
                ('licitafacil_titulo', models.CharField(max_length=100)),
                ('licitafacil_texto', models.TextField()),
            ],
        ),
    ]
