# Generated by Django 4.1.4 on 2023-01-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_plataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='titulo_inicial',
            field=models.CharField(max_length=100),
        ),
    ]
