# Generated by Django 4.1.4 on 2023-02-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0012_alter_emailcontato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
