# Generated by Django 4.1.4 on 2023-02-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_alter_emailcontato_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='botao1',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plataforma',
            name='botao2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plataforma',
            name='botao3',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plataforma',
            name='botao4',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plataforma',
            name='botao5',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
