# Generated by Django 4.1.4 on 2023-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_plataforma_botao1_plataforma_botao2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='logo_img',
            field=models.ImageField(default=1, upload_to='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plataforma',
            name='logo_title',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
