# Generated by Django 4.1.4 on 2023-03-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_plataforma_logo_img_plataforma_logo_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='EmailContato',
        ),
    ]
