# Generated by Django 4.1.4 on 2023-03-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0019_remove_secao2_servicos_remove_secao2_subtitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secao2',
            name='cards',
        ),
        migrations.AddField(
            model_name='secao2',
            name='cards',
            field=models.ManyToManyField(related_name='secao_card', to='plataforma.card'),
        ),
    ]
