# Generated by Django 4.1.4 on 2023-03-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0023_remove_secao2_cards_card_secao_secao2_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Seção 4 - Contatos',
            },
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name_plural': 'Serviços'},
        ),
    ]
