# Generated by Django 4.1.4 on 2023-03-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0024_secao4_alter_servicos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao4',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
