# Generated by Django 4.1.4 on 2023-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0025_alter_secao4_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='descricao',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
