# Generated by Django 4.1.4 on 2023-03-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0026_card_descricao_card_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name_plural': 'Add seus serviços'},
        ),
        migrations.AddField(
            model_name='secao2',
            name='descricao',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secao2',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secao2',
            name='secao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.servicos'),
        ),
        migrations.AddField(
            model_name='secao2',
            name='subtitulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secao2',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
