# Generated by Django 4.1.4 on 2023-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0028_rename_secao_secao2_itens_remove_secao2_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secao2',
            name='itens',
        ),
        migrations.AddField(
            model_name='secao2',
            name='itens',
            field=models.ManyToManyField(related_name='secao_servicos', to='plataforma.servicos'),
        ),
    ]
