# Generated by Django 4.1.4 on 2023-03-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0029_remove_secao2_itens_secao2_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao2',
            name='preco',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
