# Generated by Django 4.1.4 on 2023-03-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0030_secao2_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('paragrafo', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Seção 4 - Nosso diferencial',
            },
        ),
    ]
