# Generated by Django 4.1.4 on 2023-03-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0031_secao3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plataforma',
        ),
        migrations.AlterModelOptions(
            name='secao3',
            options={'verbose_name_plural': 'Seção 3 - Nosso diferencial'},
        ),
    ]
