# Generated by Django 4.1.4 on 2023-03-04 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0033_secao5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secao2',
            old_name='descricao',
            new_name='saibamais',
        ),
    ]
