# Generated by Django 4.1.4 on 2023-03-04 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0034_rename_descricao_secao2_saibamais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secao2',
            old_name='saibamais',
            new_name='saiba_mais',
        ),
    ]
