# Generated by Django 4.1.4 on 2023-03-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0035_rename_saibamais_secao2_saiba_mais'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao1',
            name='banner',
            field=models.ImageField(blank=True, upload_to='banner'),
        ),
    ]
