# Generated by Django 4.1.4 on 2023-03-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_secao1_secao2_secao3_secao4_secao5_servicos_and_more'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.secao2')),
            ],
            options={
                'verbose_name_plural': 'Clientes cadastrados',
            },
        ),
        migrations.CreateModel(
            name='EmailContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=100)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Formulários de contato',
            },
        ),
        migrations.CreateModel(
            name='Newslatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Inscrições newslatter',
            },
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
