# Generated by Django 4.1.4 on 2023-03-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='cnpj',
        ),
    ]
