# Generated by Django 4.1.4 on 2023-03-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cadastro_cnpj'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='Cliente',
        ),
    ]
