# Generated by Django 4.1.4 on 2023-03-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0035_rename_saibamais_secao2_saiba_mais'),
        ('clientes', '0003_rename_cadastro_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.secao2'),
        ),
    ]
