# Generated by Django 4.1.4 on 2023-03-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
